const SettingsPage = () => {
  return (
    <div className="">
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
      <h1>Settings</h1>
    </div>
  );
};

export default SettingsPage;
